### PR TITLE
Update de.json

### PR DESCRIPTION
**Pull request by ToMoReKe**
Made some changes.....

### CODE REVIEW

**Comment by aleksey-hoffman** [comment]
Good job!

**Comment by aleksey-hoffman** [comment]
Are you planning on adding more changes, or should I merge the PR?

**Comment by ToMoReKe** [comment]
By now its all. But maybe later this day or in the next Days I will correct more.

 

 
 

Gesendet: Montag, 20. Februar 2023 um 10:25 Uhr
Von: "Aleksey Hoffman" ***@***.***>
An: "aleksey-hoffman/sigma-file-manager" ***@***.***>
Cc: "ToMoReKe" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [aleksey-hoffman/sigma-file-manager] Update de.json (PR #212)


 

Are you planning on adding more changes, or should I merge the PR?

**Comment by aleksey-hoffman** [comment]
Let's keep it open then, for now. Then merge all the changes at once
Thanks, mate

**Comment by ToMoReKe** [comment]
How can I gon with my changes? It´s all a bit confusing for a newbie.....

 

 
 

Gesendet: Montag, 20. Februar 2023 um 10:30 Uhr
Von: "Aleksey Hoffman" ***@***.***>
An: "aleksey-hoffman/sigma-file-manager" ***@***.***>
Cc: "ToMoReKe" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [aleksey-hoffman/sigma-file-manager] Update de.json (PR #212)


 

Let's keep it open then, for now. Then merge all the changes at once
Thanks, mate

**Comment by aleksey-hoffman** [comment]
Do you mean you want to see your changes in the app?
For this, I have to accept your changes first and then they will appear in the next update.

I'm thinking about adding a system that would immidiately update localization changes in the app, so users don't have to wait for the next update.

**Comment by ToMoReKe** [comment]
No, I wanted to go on with the correction. But when I go to the translation-site and open the

de.json it´s (of course) without my corrections so far. Somewhere I found my Update de.json,

witch contains my corrections. But not the rest of the de.json. Is there somewhere a temporary

de.json witch contains my corrections so far and the rest of the de.json where i can go on correcting?

 
 

Gesendet: Montag, 20. Februar 2023 um 11:13 Uhr
Von: "Aleksey Hoffman" ***@***.***>
An: "aleksey-hoffman/sigma-file-manager" ***@***.***>
Cc: "ToMoReKe" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [aleksey-hoffman/sigma-file-manager] Update de.json (PR #212)


 

Do you mean you want to see your changes in the app?
For this, I have to accept your changes first and then they will appear in the next update.

I'm thinking about adding a system that would immidiately update localization changes in the app, so users don't have to wait for the next update.

**Comment by aleksey-hoffman** [comment]
There's 2 ways you can keep editing your changes:

## Method 1
1. I need to merge your changes (your branch) to the main branch, and then they will be visible there.
2. Then you add more changes (which will create a new branch) and we repeat this process.

## Method 2
1. Go to `pull requests`, and open your pull request
2. Press `/` on your keyboard to open cloud editor.

image


I just merged your changes to the main branch, now you cannt modify your first changes, but you can follow the `Method 1` described above to create a new branch with more changes,

**Comment by aleksey-hoffman** [comment]
There's 2 ways you can keep editing your changes:

## Method 1
1. I need to merge your changes (your branch) to the main branch, and then they will be visible there.
2. Then you add more changes (which will create a new branch) and we repeat this process.

I just merged your changes to the main branch, now you cannot modify your changes on this branch (cannot use `Method 2` for this branch), but you can follow the `Method 1` to create a new branch with more changes,

## Method 2
1. Go to `pull requests`, and open your pull request
2. Press `/` on your keyboard to open cloud editor.

image

**Comment by aleksey-hoffman** [comment]
I just merged this branch to the main branch, now you cannot modify your changes on this branch, but you can follow the `Method 1` to create a new branch with more changes,

**Comment by aleksey-hoffman** [comment]
This is your first branch:
https://github.com/aleksey-hoffman/sigma-file-manager/pull/212

- The changes were added to the main branch
- You will now see the changes where you started

This branch will now be displayed in the "Closed" section:

image

**Pull request merged**
