### PR TITLE
Its available for me! :)

### PR DESCRIPTION
**Pull request by mikecann**

### CODE REVIEW

**Comment by aleksey-hoffman** [comment]
Hi, are you sure v1.5 is available there? You can check the version either on the app page in store or in the app tray menu.

The v1.4.1 test build was already in MS store, I wouldn't recommend using that one

**Comment by aleksey-hoffman** [comment]
Hi, Mike
Are you sure v1.5 is available there? You can check the version either on the app page in store or in the app tray menu.
The v1.4.1 test build was already in MS store, I wouldn't recommend using that one

**Comment by mikecann** [comment]
ahh okay, apologies, I didnt realise it a specific version you were referring to. Ill close the PR

**Comment by aleksey-hoffman** [comment]
@mikecann Now it's available in MS store :)
BTW, I already uncommented the links

**Pull request closed without merging**
