### PR TITLE
Fix 'Device not ready' error

### LINKED ISSUE #1: [Problem report] Error: The device is not ready.
First issue 😎

## System info:
- **App version**: `1.0.0` 
- **Operating System**: `Win10 Pro N 20H2 19042.928` 

## Problem:
As a WinGet package maintainer i wanted to add Sigma as a package.
The validation process requires to test the package in a VM/Sandbox, the program installed fine, but it cannot find the drives and this error pops up.
image

### LINKED ISSUE #2: [Problem report] It gives an error for an USB drive on every start up
## System info:
- **App version**: `1.0.0` 
- **Operating System**: `x64 | Windows 10`

## Problem:
```
Error: Error: EISDIR, Das GerÃ¤t ist nicht bereit.
 'F:/'
    at o.fetchStorageDevices (app://./index.bundle.js:1:48802)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async o.mounted (app://./index.bundle.js:1:22620)
```
Note: If trying to use it in Windows explorer it says: Please insert drive.

### LINKED ISSUE #10: Doesnt find any drives
## System info:
- **App version**: 1.0.0 -->
- **Operating System**: Windows 10 Pro (19042.985)

## Problem
Error: Error: EISDIR, The device is not ready.
 'T:/'
    at o.fetchStorageDevices (app://./index.bundle.js:1:48802)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async o.mounted (app://./index.bundle.js:1:22620)

### LINKED ISSUE #12: just reporting a startup error
Error: Error: EISDIR, The device is not ready.
 'G:/'
    at o.fetchStorageDevices (app://./index.bundle.js:1:48802)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async o.mounted (app://./index.bundle.js:1:22620)

### LINKED ISSUE #13: Problem with disk drives, they're not found!
Error: Error: EISDIR, Ð£ÑÑÑÐ¾Ð¹ÑÑÐ²Ð¾ Ð½Ðµ Ð³Ð¾ÑÐ¾Ð²Ð¾.
 'E:/'
    at o.fetchStorageDevices (app://./index.bundle.js:1:48802)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async o.mounted (app://./index.bundle.js:1:22620)
Снимок экрана (5)
_**Thank you for this file manager, it's look amazing, but i can not do anything with they until you fix the problem.**_

### PR DESCRIPTION
**Pull request by btglr**
Filters out any drive that has an empty fsType on Windows.
Additionally, sets the available, free and total size to 0 if diskusage.check raises an error.

Feel free to change whatever needs to be changed if you want to handle it any other way.

Fixes #1
Fixes #2
Fixes #10
Fixes #12
Fixes #13

### CODE REVIEW

**Comment by aleksey-hoffman** [comment]
Thank you for the PR. Have you tested it locally? Is it actually fixing those problems?

**Comment by aleksey-hoffman** [comment]
Also, can you please add these into PR description:

Fixes #2
Fixes #10
Fixes #12
Fixes #13

**Comment by btglr** [comment]
> Thank you for the PR. Have you tested it locally? Is it actually fixing those problems?

Yes, I've tested it and it fixes the problem and allows the drives to load. I don't have a CD/DVD drive though so it'd be nice if someone could try out the PR.

Nevertheless there's probably a more elegant way to handle the problem. For example, do you intend to display RAW drives the same way the Windows Explorer does it? What about CD/DVD drives?

Right now I'm simply filtering those out which means they're not displayed at all.

**Comment by aleksey-hoffman** [comment]
> For example, do you intend to display RAW drives the same way the Windows Explorer does it? What about CD/DVD drives?

Perhaps there are some other NPM modules I could use that can not only detect regular drives but also things like CD/DVD. 
Or maybe I should just get the drive list using powershell commands. But I feel like it would take 100+ ms per call, which would be too slow, considering the drive data is updating once every second.

**Comment by aleksey-hoffman** [comment]
Merging it for now since the issue is affecting a lot of people. 
Will add support for CD/DVD and raw drives later.

Thank you very much for the fix!

**Comment by btglr** [comment]
> Perhaps there are some other NPM modules I could use that can not only detect regular drives but also things like CD/DVD.

The CD/DVD drives are correctly detected, the problem comes from `diskusage` attempting to check the free/available/total size for those drives as if they were hard drives. Anyway, I booted up a Windows 10 VM with a DVD drive and the fix works as it filters it out.

**Comment by aleksey-hoffman** [comment]
@btglr thanks mate. I understand it now. Didn't really sleep for 2 days, so I was a little slow yesterday.

I agree that a more elegant way of handling this would have to be added later.

Thank you for tour help

**Pull request merged**
