### PR TITLE
Update de.json

### PR DESCRIPTION
**Pull request by ToMoReKe**
Somtimes difficult to decide wich german word is the best. Is there a way to see, where the debatable text occurs in sigma? Somtimes its obvious, but often not.

### CODE REVIEW

**Comment by minisbett** [comment]
I cannot recommend merging this. A lot of translation are made worse than before.

**Comment by aleksey-hoffman** [comment]
The best way to find where a specifc line of text is occuring is to search the text you can already see in Sigma UI. For example:

1. Go to Settings page
2. See where the text of line is located to better understand how it should be translated
3. Go to the tranlation file, 
4. Find the line of text in the English `en.json` file using `Ctrl + F` and only then translate it in the target translation file.

image

image

**Comment by ToMoReKe** [comment]
For example?

 
 

Gesendet: Montag, 20. Februar 2023 um 15:37 Uhr
Von: "minisbett" ***@***.***>
An: "aleksey-hoffman/sigma-file-manager" ***@***.***>
Cc: "ToMoReKe" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [aleksey-hoffman/sigma-file-manager] Update de.json (PR #213)


 

I cannot recommend merging this. A lot of translation are made worse than before.

**Comment by minisbett** [comment]
I did a PR to improve some more translation and fix some of these, but overall I think this can be merged if my PR gets merged afterwards.

**Comment by aleksey-hoffman** [comment]
Thanks guys, I will merge the changes now

**Pull request merged**
